version: '3.9'

networks:
  ipam_ipvlan:
    driver: ipvlan
    driver_opts:
      ipvlan_mode: "l2"
      parent: ${NETWORK_IF}
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
          gateway: ${SUBNET_GW}

services:
  phpipam-db:
    image: mariadb:latest
    container_name: phpipam-db
    environment:
      - TZ=Europe/Warsaw
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%
    restart: unless-stopped
    networks:
      default:
    volumes:
      - ${PWD}/phpipam/db:/var/lib/mysql
      - ${PWD}/power_dns/schema.mysql.sql:/docker-entrypoint-initdb.d/pdns-db_init.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'SHOW DATABASES;' | `which mariadb` --user=root --password=${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  phpipam-web:
    build: ./phpipam
    container_name: phpimap-web
    environment:
      - TZ=Europe/Warsaw
      - IPAM_DATABASE_HOST=phpipam-db
      - IPAM_DATABASE_PASS=${IPAM_DATABASE_PASS}
      - IPAM_DATABASE_WEBHOST=%
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -L http://localhost | grep -q -i 'login'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      default:
    ports:
      - "8001:80"
    depends_on:
      phpipam-db:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  powerdns-server:
    build: ./power_dns
    container_name: pdns-server
    hostname: pdns-server
    restart: unless-stopped
    depends_on:
      phpipam-db:
        condition: service_healthy
    environment:
      - TZ=Europe/Warsaw
      - PDNS_LOG_LEVEL=10
      - PDNS_WEBSERVER_ALLOWED_FROM=${PDNS_ALLOWED_IP}
      - PDNS_WEBSERVER_PASSWORD=${PDNS_WEBSERVER_PASSWORD}
      - PDNS_API_KEY=${PDNS_API_KEY}
      - PDNS_MYSQL_HOST=${PDNS_MYSQL_HOST}
      - PDNS_MYSQL_PORT=${PDNS_MYSQL_PORT}
      - PDNS_MYSQL_DB=${PDNS_MYSQL_DB}
      - PDNS_MYSQL_USER=${PDNS_MYSQL_USER}
      - PDNS_MYSQL_PASSWORD=${PDNS_MYSQL_PASSWORD}
      - PDNS_MYSQL_DNSSEC=DNSSEC
    networks:
      ipam_ipvlan:
        ipv4_address: ${PDNS_SERVER_IP}
      default:
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8081:8081/tcp"
    volumes:
      - ${PWD}/power_dns/log:/var/log
      - ${PWD}/power_dns/pdns.conf:/etc/pdns/pdns.conf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  powerdns-recursor:
    build: ./power_recursor
    container_name: pdns-recursor
    hostname: pdns-recursor
    restart: unless-stopped
    environment:
      - TZ=Europe/Warsaw
      - PDNS_LOG_LEVEL=10
      - PDNS_WEBSERVER_ALLOWED_FROM=${PDNS_ALLOWED_IP}
      - PDNS_API_KEY=${PDNS_API_KEY}
    networks:
      ipam_ipvlan:
        ipv4_address: ${PDNS_RECURSOR_IP}
    ports:
      - "8082:8082/tcp"
    volumes:
      - ${PWD}/power_recursor/log:/var/log
      - ${PWD}/power_recursor/recursor.conf:/etc/pdns/recursor.conf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
